### ISSUE TITLE
Error attempting to read response when empty.

### ISSUE THREAD

**Issue by jfloodnet** [vespaiach/axios-fetch-adapter#13]
If responseType is set, but the response is empty, this library throws an error.

```
SyntaxError: Unexpected end of JSON input
    at getResponse (index.js:72:1)
    at async fetchAdapter (index.js:29:1)
```

**Comment by vespaiach** [comment]
That SyntaxError was expected to be thrown. Let's see here https://github.com/github/fetch/issues/378
