### ISSUE TITLE
Headers are gone using this adapter with axios

### ISSUE THREAD

**Issue by mario-vieira** [vespaiach/axios-fetch-adapter#23]
Hi,

I'm using this adapter with axios in order to make a browser extension work with manifest v3.
However, after that change the headers are empty. 

Here's the code:

```
import fetchAdapter from '@vespaiach/axios-fetch-adapter';
const axiosInstance = Axios.create({
            adapter: fetchAdapter,
            baseURL: `https://${hostname}`,
            withCredentials: true
        });
```

Then if I check the response the headers are empty. Can you help?

**Comment by kishoreKlkr** [comment]
@mario-vieira can you mentioned how this issue resolved?. Please

**Comment by harismuha123** [comment]
@mario-vieira I'm also curious, did you manage to resolve this?
