### ISSUE TITLE
Support for disabling redirects

### ISSUE THREAD

**Issue by sunkan** [vespaiach/axios-fetch-adapter#3]
I don't know if this is a bug but this looks wrong in the code

https://github.com/vespaiach/axios-fetch-adapter/blob/f6724dd0ed5f1788000d43b53ff49f162e224770/src/createRequest.js#L35-L37

Do you want  a pull-request that fixes this?

**Comment by vespaiach** [comment]
Thanks @sunkan, just pushed a fix for it
