### ISSUE TITLE
Why yarn add @vespaiach/axios-fetch-adapter not found index.d.ts

### ISSUE THREAD

**Issue by godfox2012** [vespaiach/axios-fetch-adapter#6]
Why yarn add @vespaiach/axios-fetch-adapter not found index.d.ts

Enviroment:
  macOS Catalina
  nextjs 12

**Comment by aldyrmbe** [comment]
Having the same issue

**Comment by vespaiach** [comment]
fixed in [v0.2.2](https://github.com/vespaiach/axios-fetch-adapter/releases/tag/v0.2.2)
